### ISSUE TITLE
Problems in Pipeline when updating snap-deploy, started this morning

### ISSUE THREAD

**Issue by pameck** [snap-ci/snap-deploy#15]
$ snap-deploy update
Fetching origin
From git://github.com/snap-ci/snap-deploy
   135c734..f40230e  release    -> origin/release
   7a3ff1a..f40230e  master     -> origin/master
 * [new tag]         v0.1.4     -> v0.1.4
error: Your local changes to the following files would be overwritten by merge:
	Gemfile.lock
Please, commit your changes or stash them before you can merge.
Aborting
Updating 135c734..f40230e
/opt/local/snap-deploy/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/file_utils.rb:54:in `block in create_shell_runner': Command failed with status (1): [sudo $(which git) merge --ff-only origin/r...] (RuntimeError)
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/file_utils.rb:45:in `call'
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/file_utils.rb:45:in `sh'
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/file_utils_ext.rb:37:in `sh'
	from /opt/local/snap-deploy/lib/snap_deploy/provider/update.rb:20:in `block in execute'
	from /opt/local/ruby/2.0.0-p598/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
	from /opt/local/ruby/2.0.0-p598/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/file_utils_ext.rb:37:in `cd'
	from /opt/local/snap-deploy/lib/snap_deploy/provider/update.rb:18:in `execute'
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /opt/local/snap-deploy/bundle/ruby/2.0.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /opt/local/snap-deploy/bin/snap-deploy:10:in `<main>'

**Comment by pameck** [comment]
Magically fixed now
